# Introduction

## Rationale {#rationale}

```{r introduction-rationale, echo = FALSE, child = "introduction/_rationale.Rmd"}
```

## Background {#background}

```{r introduction-background, echo = FALSE, child = "introduction/_cancer-theory.Rmd"}
```

```{r introduction-somatic-mutations, echo = FALSE, child = "introduction/_somatic-mutations.Rmd"}
```

```{r introduction-disrupted-context, echo = FALSE, child = "introduction/_disrupted-context.Rmd"}
```

```{r introduction-stem-cells, echo = FALSE, child = "introduction/_stem-cells.Rmd"}
```

```{r introduction-regeneration, echo = FALSE, child = "introduction/_muscle-regeneration.Rmd"}
```

```{r introduction-mirna, echo = FALSE, child = "introduction/_mirna.Rmd"}
```

```{r introduction-epigenetics, echo = FALSE, child = "introduction/_epigenetics.Rmd"}
```

```{r introduction-integrated-analysis, echo = FALSE, child = "introduction/_integrated-analysis.Rmd"}
```

## Lack of knowledge and objectives

```{r introduction-objectives, echo = FALSE, child = "introduction/_objectives.Rmd"}
```

## Thesis contributions

```{r introduction-contrib, echo = FALSE, child = "introduction/_contributions.Rmd"}
```

## Results and discussion

```{r introduction-results, echo = FALSE, child = "introduction/_results.Rmd"}
```

## Conclusion

```{r introduction-conclusion, echo = FALSE, child = "introduction/_conclusion.Rmd"}
```

## References {-}
