# Publications

## MIRPIPE: quantification of microRNAs in niche model organisms

Carsten Kuenne^1,‡^, Jens Preussner^1,‡^, Mario Herzog^1^, Thomas Braun^2^ and Mario Looso^1^

------------------    ---------------------------------------------------------------------------------------------------------------------
**Affiliations**      ^1^ Group of Bioinformatics and
                      ^2^ Department of Cardiac Development and Remodelling 
                          Max Planck Institute for Heart and Lung Research
                      ^‡^ These authors contributed equally
**Journal**           Bioinformatics, *Oxford Journals*
**Date, Issue**       2014, Vol. 30 no. 23
**Pages**             3412 - 3413
**DOI**               10.1093/bioinformatics/btu573
------------------    ---------------------------------------------------------------------------------------------------------------------


#### Contributed to
implementation, data analysis, writing

\includepdf[pages={-}]{publications/2014_mirpipe.pdf}

## ADMIRE: analysis and visualization of differential methylation in genomic regions using the Infinium HumanMethylation450 Assay

Jens Preussner^1^, Julia Bayer^1^, Carsten Kuenne^1^ and Mario Looso^1^

------------------    ---------------------------------------------------------------------------------------------------------------------
**Affiliations**      ^1^ Group of Bioinformatics
                          Max Planck Institute for Heart and Lung Research
**Journal**           Epigenetics and Chromatin, *BioMed Central*
**Date, Issue**       2015, Vol. 8 no. 1
**Pages**             1 - 10
**DOI**               10.1186/s13072-015-0045-1
------------------    ---------------------------------------------------------------------------------------------------------------------

#### Contributed to
implementation, data analysis, writing

\includepdf[pages={-}]{publications/2015_admire.pdf}

## A molecular subtype of cancer originating from adult stem cells during regeneration is driven by Dux transcription factors

Jens Preussner^1,2,‡^, Jiasheng Zhong^1,‡^, Krishnamoorthy Sreenivasan^1^, Stefan Günther^1,3^, Thomas Engleitner^4^, Carsten Künne^1,2^, Markus Glatzel^5^, Roland Rad^4^, Mario Looso^2^, Thomas Braun^1,6,7^ and Johnny Kim^1,6^*

------------------    ---------------------------------------------------------------------------------------------------------------------
**Affiliations**      ^1^ Department of Cardiac Development and Remodelling
                      ^2^ Bioinformatics Core Unit (BCU)
                      ^3^ ECCPS Deep Sequencing Platform
                          Max Planck Institute for Heart and Lung Research
                      ^4^ Institute of Molecular Oncology and Functional Genomics
                          Translatum Cancer Center and Department of Medicine II
                          Technical University of Munich
                      ^5^ Institute of Neuropathology
                          University Medical Center Hamburg-Eppendorf
                      ^6^ German Center for Cardiovascular Research (DZHK)
                      ^7^ German Center for Lung Research (DZL)
                      ^‡^ These authors contributed equally
**Journal**           Cell Stem Cell, *Cell Press*
**Date, Issue**       2018, Vol. 23 no. 6
**Pages**             794 - 805
**DOI**               10.1016/j.stem.2018.10.011
------------------    ---------------------------------------------------------------------------------------------------------------------

#### Contributed to
data analysis, writing

\includepdf[pages={-}]{publications/2018_duxbl.pdf}
