## Thesis reviewers {-}

#### First reviewer
Prof. Dr. Alexander Goesmann, *Bioinformatics and Systems Biology, Justus-Liebig-University, Giessen, Germany*

#### Second reviewer
Prof. Dr. Dr. Thomas Braun, *Max Planck Institute for Heart and Lung Research, Bad Nauheim, Germany*

#### Examiner
Prof. Dr. Reinhard Dammann, *Institute for Genetics, Justus-Liebig-University, Giessen, Germany*

#### Examiner
Prof. Dr. Stefan Janssen, *Algorithmic Bioinformatics, Justus-Liebig-University, Giessen, Germany*

## Declaration {-}

I declare that I have completed this dissertation single-handedly without the unauthorized help of a second party and only with the assistance acknowledged therein. I have appropriately acknowledged and cited all text passages that are derived verbatim from or are based on the content of published work of others, and all information relating to verbal communications. I consent to the use of an anti-plagiarism software to check my thesis. I have abided by the principles of good scientific conduct laid down in the charter of the Justus Liebig University Giessen "Satzung der Justus-Liebig-Universität Giessen zur Sicherung guter wissenschaftlicher Praxis" in carrying out the investigations described in the dissertation.

