---
title: "Development and application of computational methods for cancer subtype detection from -omics data"
#title: "Methods for data analysis in high throughput-omics applications"
author: "Jens Preussner"
date: "Bad Nauheim, 2020"
papertype: Cumulative inaugural dissertation
degree: Doctor rerum naturalium (Dr. rer. nat.)
submitted-to-text: submitted to the
submitted-to: |
  Faculty of Biology and Chemistry

  Justus-Liebig-University

  Giessen, Germany

prepared-at-text: prepared in the
prepared-at: |
  Department of Cardiac Remodelling

  Max Planck Insititute for Heart and Lung Research

  Bad Nauheim, Germany

site: bookdown::bookdown_site
logo: header-thesis.pdf
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("_abstract.Rmd"), collapse = '\n  ')`
preface: | 
  `r if(knitr:::is_latex_output()) paste(readLines("_preface.Rmd"), collapse = '\n  ')`
chapterstyle: southall
bibliography: ["bib/Rationale.bib", "bib/Background.bib", "bib/Objectives.bib", "bib/Discussion.bib"]
biblio-style: "apalike"
# biblio-style: "authoryear"
# biblatexoptions: [refsegment=chapter]
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
```

```{r env, echo = FALSE}
#Sys.setenv(RSTUDIO_PDFLATEX="latexmk")
```
