The foundation of modern oncology, i.e. cancer classification, diagnosis, therapy and research, was laid out in the early nineteenth century by Johannes Müller, a professor of anatomy and pathology and Director of the Royal Anatomical Museum in Berlin. Using microscopic pathology to examine tissues of *morbid growth*, Müller recognised, for the first time, the cellular structure of cancer and how it resembled the tissue from which the cancerous growth springs. The origin of cancer and its development has since then been subject of debate in several theories, most of which seeking its origin in a transformation of a healthy cell into a disease state characterised by uncoordinated and excessive cell growth.

### Somatic mutations transform cells into cancer cells

While normal cells retain their ability to control the production and release of growth-promoting signals, and thereby provide tissue architecture and homeostasis of cell number, cancer cells are characterised by chronic proliferation and constant entry and progression through the growth-and-division cycle. The somatic mutation theory assumes that molecular events preceed cell transformation and provide the cell with enabling abilities. By such, transformed cancers cells are able to e.g. escape the control of growth supressors, bypass mechanism of induced cell death, delay or avoid entry into cell senescence, induce angiogenesis and/or alter cell-to-cell contacts to activate invasion of surrounding tissue. At the core of this theory, mutations in so-called master genes (e.g. oncogenes or tumor supressor genes) constitute the origin of cancer. 
Molecular alterations in a single somatic cell are passed onto its progeny and therefore must be heritable to enable clonal expansion (elaborate more on this) and promote cancer growth by sequential accumulation of transforming changes. The mechanism of heredity is not limited to genetic alterations but can also be of epigenetic origin, i.e. based on changes in methylation, acetylation or chromatin structure as well (xref). Importantly, heredity exposes cancer cells to natural selection and enables evolutionary mechanisms to act on cancer development. 

The search for transformation-causing genome alterations accelerated through recent advances in high-throughput technologies which led to an impressive accumulation of data from large-scale genome sequencing projects like the [Cancer Genome Project](cancer.sanger.ac.uk) or [The Cancer Genome Atlas](cancergenome.nih.gov). Collectively, both projects list 77 million simple somatic mutations across cancer genomes from nearly 25,000 individuals in the International Cancer Genome Consortium [Data Portal Release 27](https://dcc.icgc.org/releases/release_27). However and until today, the search did not reveal a single pattern of genetic alterations that is universal to most cancers. Instead, it revealed tremendous genetic heterogeneity in underlying mechanisms of cancer formation despite very similar phenotypes.

Following the observed genetic heterogeneity among cancer and even within similar cancer types, it can be reasoned that most individual tumors exhibit different genome contexts with alterations in e.g. genes, regulatory elements and genomic topology. Genome context is largely defined by a cells karyotype and together, both observations provide an underpinning for observed heterogeneity in cancer. 
The Genome Theory extends the somatic mutation theory by karyotype heterogeneity and the process of natural selection into a new theory on how somatic cells evolve within individual patients [@heng_evolutionary_2010]. At the core of the evolutionary mechanism is genome context instability induced by internal (e.g. elicited through somatic mutations) or external (e.g. treatment, environment) stress. As a consequence, genetic or epigenetic alterations increase cell population heterogeneity to ultimately enable natural selection of somatic cells showing high fitness in terms of survival or proliferation. The evolutionary mechanism happens in two steps of karyotypic evolution:
1) the punctuated (unstable) phase, characterised by high genome-level heterogeneity between individual cells and
2) the stepwise (relatively stable) phase, where dominant karyotypes emerge and accumulate minor modifications over time.

The occurence of genome-level alterations in an instable genome context is a stochastic process and therefore the probability of successful progression towards cancer is highest through alterations significantly impacting a cells phenotype. Concomitantly, the stochastic nature complicates the prediction of which pathway will become dominant prior to tumor formation and renders the characterization of individual cancer pathways less meaningful. Ultimetaly, it impedes the formulation of a general mechanism of cancer origin and obscures understanding of how cancer can be managed in classical clinical treatment.

### Disrupted context: Cancer as a tissue-based disease {#development}

Organs and higher-level structures are comprised of tissue with functional (parenchyme) and structural (stroma) parts. Information exchange between cells of a tissue via cell-to-cell contacts, cytokine signalling and the extracellular matrix, a macromolecular scaffold to support surrounding cells, provides context to maintain cell differentiation and tissue structure. Tissue-level interactions are important for embryonic development and morphogenesis, e.g. to provide neccessary mechanical forces for proper tissue formation and hence, are inextricably linked to the 3D structure and developmental history of the underlying tissue. Disruption of tissue organisation is thought to be carcinogenic through entailed disruption of tissue-level interactions. 

The physiomitotic theory of cancer relates the acquisition of mitotic activities to development of cancer by non-regulated cell turnover among normal tissue [@hirata_physio-mitotic_2002]. Two types of mitosis maintain tissue histology and continuity: duplicating mitosis regenerates a basal pool of undifferentiated cells in a space-restricted duplication area by creating two identical daugther cells. Those cells are constantly consumed in surrounding areas by maturating mitosis, which creates two daughter cells that are more mature than the parent cell and contribute to tissue diversity and functionality via cell differentiation. 
Disrupted tissue organization and regulation may evoke duplicating mitosis at ectopic sites among normal tissue, thereby creating newly and aberrant tissue identity and non-regulated cell turnover and maturation into cancerous tissue. Carcinogenesis is seen as a problem of tissue organization.  

Similarly, the tissue organization field theory argues that interactions among different tissue components cannot be explained on a cellular level and that carcinogenesis cannot be reduced to cellular events. Cancer initiation is preceeded by a carcinogenic event that chronically disrupts reciprocal interactions between stroma and parenchyme of a tissue, but cannot be observed in individual, isolated cells.

A well known example and important feature of interactions of stroma with surrounding cells is the maintenance of polarized epithelial sheets, a basic tissue type that lines outer surfaces of organs and surfaces of inner cavities. Cell polarity is established by interaction with the basement membrane and cell-to-cell contacts, like adherens junctions, gap junctions, tight junctions and desmosomes. Alterations of epithelial sheets, e.g. through wounding and subsequent activation of stromal fibroblasts, can lead to epithelial cell movement and proliferation. Similarly, sustained inflammation and continuous upregulation of factors produced by invading immune cells and enzymes degrading the EMC (e.g. matrix metalloproteinases) stimulate proliferative and apoptotic mechanisms, which can lead to selection of apoptosis-resistant, premalignant cells and enhance formation of carcinoma. Loss or downregulation of e-cadherin, an important component of adherens junctions, leads to a premalignant cell type that is prone to invasion and metastasis by passing through a epithelial-to-mesenchymal transition [@christofori_role_1999]. However, restoration of e-cadherin expression in such cells can suppress cellular transformation.

Experiments have shown that also restoration of context can lead to healthy phenotypes, e.g. normal differentiation is observed when teracarcinoma cells are injected into blastocysts, even after long passaging [@illmensee_totipotency_1976]. Similarly, experiments from 3D culturing with reconstituted basement membranes or co-culturing of malignant cells with normal stroma reverted their carcinogenic properties. In summary, these experiments suggest that normal stroma provides contextual cues that promotes normal tissue identity and restricts proliferation of existing malignant cells. Abnormal stroma function, on the other hand, releases this supression and permits neoplastic transformation [@bissell_putting_2001]. By such, carcinogenesis can possibly be reversed when neoplastic tissue comes into contact with normal tissue or components thereof.

### The stem cell as a cancer cell of origin {#csc}

Similar to maintenance of tissue identity, the development of normal tissue requires complex crosstalk between cells and their local environment, as well as the whole organ, and depends on migration and proper localization of cells to enable formation of mature descendants through cell division that can carry out their tissue-specific function. The specific pattern of a cells tissue-forming division(s) has been termed its *lineage* [@chisholm_cell_2001]. Dissection of such cell lineages revealed further a hierarchical organization and helped to identify interactions and molecular signalling pathways that are important in tissue development and diseases. However, unidirectional division along the cell lineage would quickly lead to exhaustion of a cells tissue-generative potential and calls for a mechanism like duplicating mitosis as proposed by the physiomitotic theory: **Stem cells** are unspecialized cells residing at the apex of a lineage, and are capable of both, generation of progenitor cells with increasing lineage commitment and self-renewal, to regenerate and sustain the pool of stem cells. The inherent proliferative capacity and the ability to give rise to different, mature cell types renders stem cells particularly fascinating for the study of tissue development, regeneration and in the search for the cellular origin of cancer.

Of paramount importance for tumor growth are cells with self-renewal capacity to ensure long-term clonal growth. However, not all cancer cells possess self-renewal capacity and not all cancer cells of origin were bona-fide stem cells. So, how do cancer cells acquire their stemness, if not from normal tissue stem cells? 

An important distinction has to be made between cancer cells of origin (*i.e.* the normal cell that acquires the first cancer-promoting mutation) and cancer stem cells, *i.e.* a cellular subset within the tumor that uniquely sustains malignant growth. Insights of emergence of intertumoral heterogeneity, *i.e.* the variability among discrete tumor types arising from the same tissue, has put forward two hypothesis, how cancer stem cells are formed: (A) All tumors originate from multipotent stem cells that accumuluate different genetic or epigenetic mutations through their extended longevity and therefore result in different tumor types or (B) different cells along the lineage hierarchy that still possess or can re-instigate proliferative capacity or prevent terminal differentiation (e.g. common or committed progenitor cells) upon oncogenic transformation constitute different cancer types [@perez-losada_stem-cell_2003, @visvader_cells_2011].

Both mechanisms inextricably link lineage descendance and differentiation state of precursor cells to cancer biology, such that activation of the same oncogenic pathway in tumors from different cell lineages or contexts may profoundly influence malignancy and tumor phenotype. Lineage dependency (add literature) therefore guides therapeutic approaches [@garraway_lineage_2006] ...

A straightforward approach to evaluate the oncogenic capacity of different lineage stem and precursor cell populations relies on reproducible separation of functionally defined subpopulations using e.g. cell sorting techniques. Relevant oncogenic lesions are introduced *ex vivo*, together with a flourescent reporter, into each target subpopulation and genetically altered cells are transplanted orthotopically into immunocompromised mice. Emergence of pre-neoplastic or neoplastic tissue from transduced subpopulations serves as readout for evaluation of oncogenic potential for each subpopulation. Complimentary, and with sufficient knowledge about cell-specific promoters, *in vivo* conditional targeting of cell populations is also conceivable. This approach makes use of genetic mouse models to conditionally activate either an oncogene or inactivate a tumor supressor gene, e.g. by Cre-mediated deletion, in different lineage subpopulations. Depending on the activated cell-specific promoter, different cancer subtypes might arise and reveal the cellular origin of the specifc cancer subtype from within the cell lineage. (Cite Hayashi, Visvader). However, for many tissues and organs, established lineages and knowledge of cell specific promoters are lacking, and therefore hamper the approach described above.

### Skeletal muscle regeneration as a model for stem cell tumor {#regeneration}

The ability of movement is an evolutionary advantage of all animals, and is powered by muscles. Vertebrate locomotion receives its power from striated, skeletal muscle, one of the three major muscle types in the body, that is composed from multiple bundled (fascicles) muscle fibres. Each fibre is a multinucleated muscle cell formed by fusion of differentiated mononuclear muscle cells (myoblast) and exhibits force and movement by coordinated activity of myosin II motor proteins within an actin filament scaffold. Skeletal muscle retains a remarkable ability to regenerate and adapt to changes in requirements, mediated by and dependent on muscle stem cells that reside between the muscle sarcolemma and the basal lamina of individual muscle fibres. Adult muscle stem cells are *bona fide* stem cells, being capable of both, self-renewal and myogenic differentiation, which ultimately leads to differentiated muscle cells. (Almada and Wagers, 2016; Guenther et al., 2013, Braun and Gautel, 2011)

Under homeostasis of uninjured muscle, muscle stem cells are marked by expression of Paired box protein 7 (PAX7), a transcriptional regulator that actively maintains a state of restrained cell cycling called *quiescence*. Upon muscle trauma, e.g. inflicting injury or during chronic regeneration of certain diseases, otherwise quiescent muscle stem cells become activated through exposure to extrinsic, pro-myogenic stimuli and switch to a highly proliferative state. Activation and proliferation of muscle stem cells depends on expression of two transcriptional regulators, myogenic factor 5 (MYF5) and myogenic determintation protein (MYOD), and preceedes commitment to differentiation. Downregulation of PAX7 and expression of myogenin (MYOG) in a subset of activated muscle stem cells induces differentiation and ultimately leads cell-cycle exit and formation of myoblasts that fuse with other myoblasts or existing muscle fibres to repair the muscle. Activated stem cells may also inhibit MYOD expression and re-instating quiescence, thereby replenishing the pool of muscle stem cells for future muscle repair. 

Duchenne muscular dystrophy (DMD) is a genetic disorder with severe features of muscle weakness and decrease in the mass of a muscle (muscle wasting, atrophy). Dystrophin, the gene product causing DMD in affected individuals, plays a pivotal role in anchoring muscle fibres to the extracellular matrix, thereby allowing force to be transmitted to the skeletal parts of the muscle. Dystrophic fibres are prone to damage by mechanical stress and die after repeated muscle contraction. Such fibres are often replaced by fibrotic, adipose or connective tissue that is not able to transmit sufficient muscular force. Muscle degeneration elicits repair by expansion and differentiation of stem cells, but regenerated muscle fibres also lack a functional dystophin such that chronic cycles of degeneration and regeneration are passed through. Until now, the role of muscle stem cells in DMD remains elusive, with only some evidence for specialized roles of dystrohin during the stem cell division mechanism but as well hints to an important role of the pathological environment for disease progression. (Zammit, )

A genetic and experimental model of DMD is the *mdx* mouse, whose muscles retain a lifelong capacity to regenerate fibres and exhibits loss of muscle fibres and extensive fibrosis. Recently, it was shown that germline inactivation of the tumor suppressor p53 in chronically regenerating mdx mice develop rhabdomyosarcoma (RMS) (Camboni et al., 2012; Chamberlain et al., 2007), a rare and aggressive childhood cancer and the most common soft-tissue sarcoma in children and adolescents (El Demellawy et al., 2017).

c) Rhabdomyosarcoma: What are forms of RMS? Where / When does it occur and what are the open questions regarding its origin?

d) Open questions?

### Small RNA mediated carcinogenesis

### Epigenetic mechanisms in cancer initiation and progression
