### Disrupted context: Cancer as a tissue-based disease {#development}

Organs and higher-level structures are comprised of tissue with functional (parenchyme) and structural (stroma) parts. Information exchange between cells of a tissue via cell-to-cell contacts, cytokine signalling and the extracellular matrix, a macromolecular scaffold to support surrounding cells, enables maintenance of cell differentiation and tissue structure. Tissue-level interactions are important for embryonic development, regeneration and morphogenesis, e.g. to provide neccessary mechanical forces for proper tissue formation [@hernandez-hernandezMechanicalForcesInformation2014]. Therefore, disruption of tissue organisation is thought to be carcinogenic through entailed disruption of tissue-level interactions.

The physiomitotic theory sees carcinogenesis as a problem of tissue organisation and relates the acquisition of mitotic activities to development of cancer by non-regulated cell turnover among normal tissue [@hirataPhysiomitoticTheoryNew2002]. Two types of mitosis maintain tissue histology and continuity: duplicating mitosis regenerates a basal pool of undifferentiated cells in a space-restricted duplication area by creating two identical daugther cells. Those cells are constantly consumed in surrounding areas by maturating mitosis, which creates two daughter cells that are more mature than the parent cell and contribute to tissue diversity and functionality via cell differentiation (see Figure).
Disrupted tissue organization and regulation may evoke duplicating mitosis at ectopic sites among normal tissue, thereby creating aberrant and undefined tissue identity. This might lead to non-regulated cell turnover and maturation into cancerous tissue.

Similarly, the tissue organization field theory argues that interactions among different tissue components cannot be explained on a cellular level and that carcinogenesis cannot be reduced to cellular events. Cancer initiation is preceeded by a carcinogenic event and chronically disrupts reciprocal interactions between stroma and parenchyme of a tissue, but cannot be observed in individual, isolated cells.

A well known example and important feature of interactions of stroma with surrounding cells is the maintenance of polarized epithelial sheets, a basic tissue type that lines outer surfaces of organs and surfaces of inner cavities. Cell polarity is established by interaction with the basement membrane and cell-to-cell contacts, like adherens junctions, gap junctions, tight junctions and desmosomes. Alterations of epithelial sheets, e.g. through wounding and subsequent activation of stromal fibroblasts, can lead to epithelial cell movement and proliferation. Similarly, sustained inflammation and continuous exposition to factors produced by invading immune cells and enzymes degrading the EMC (e.g. matrix metalloproteinases) stimulate proliferative and apoptotic mechanisms, which can lead to selection of apoptosis-resistant, premalignant cells and enhance formation of carcinoma (see figure). Loss or downregulation of e-cadherin, an important component of adherens junctions, leads to a premalignant cell type that is prone to invasion and metastasis by passing through a epithelial-to-mesenchymal transition [@christoforiRoleCelladhesionMolecule1999]. However, restoration of e-cadherin expression in such cells can suppress cellular transformation.

Experiments have shown that also restoration of cell environment can lead to healthy phenotypes, e.g. normal differentiation is observed when teracarcinoma cells are injected into blastocysts, even after long passaging [@illmenseeTotipotencyNormalDifferentiation1976]. Similarly, experiments from 3D culturing with reconstituted basement membranes or co-culturing of malignant cells with normal stroma reverted their carcinogenic properties [@weaverReversionMalignantPhenotype1997]. In summary, these experiments suggest that normal stroma provides contextual cues that promotes normal tissue identity and restricts proliferation of existing malignant cells. In contrast, non-functional stroma releases this supression and permits neoplastic transformation [@bissellPuttingTumoursContext2001]. These findings lead to the hypothesis that carcinogenesis might be reversed when neoplastic tissue comes into contact with functional tissue or components thereof.
