### Cancer subtype classification using integrated molecular analysis  

Identification and assignment of a tumour's molecular subtype is seen as an important step towards *precision medicine* and a prerequisite for tailoring therapy to individual patients [@vincentComingEraPrecision2017;@senftPrecisionOncologyRoad2017]. Traditional clinical practice from the last decades largely based the identification and assignment of tumor subtype on histopathology, cytology and expression or mutational status of known tumour markers, with the outcome often being determined by the individual expertise of clinicians and the classification scheme used [@ellisImpactNationalExternal2006]. With the advent of NGS technology and the establishment of novel clinical routines for sample processing and data analysis, the molecular characterization of tumours became feasible [@noushmehrIdentificationCpGIsland2010;@pratDeconstructingMolecularPortraits2011] and promises to fulfil two goals of *precision medicine*: First, the discovery of molecular biomarkers being predictive of patient outcome or effective drug treatment and second, a better mechanistic understanding of the molecular basis of tumour initiation and progression [@senftPrecisionOncologyRoad2017].

Increasing scale of NGS-based high-throughput assays has so far been useful in dissection of tumour heterogeneity. Although genome-wide screening of mutational status [@kuijjerCancerSubtypeIdentification2018], miRNA expression [@blenkironMicroRNAExpressionProfiling2007], DNA methylation [@zhangSpecificBreastCancer2018] and RNA expression have led to the characterization of many cancer subtypes, the characterization of cancer using a single assay might suffer from certain limitations. For example, genomic profiling alone detects the presence or absence of genetic drivers, but fails to predict the activity of corresponding proteins and pathways. Simultaneous characterization using two or more assays might overcome those limitations and enhance clinical decision making towards targeted therapy, but requires effective integration strategies. 

Data integration aims at combining data from different sources, thereby enhancing accessibility and possibly enriching results from queries. Data is typically integrated across two axis: vertically, i.e. between different data types (e.g. genomic data, expression data or clinical data) and/or horizontally, i.e. within the same datatype, but across data from e.g. different providers, batches, etc. [The Cancer Genome Atlas](cancergenome.nih.gov) Research Network provides a large collection of tumour samples that have been characterized using multiple high-throughput assays [@hoadleyCellofOriginPatternsDominate2018] and have been generated across multiple data generation centers. An early approach for vertical data integration used results from separate clustering of data types and performs a clustering of cluster assignments (CoCA, @hoadleyMultiplatformAnalysis122014a). However, such an approach would not benefit from synergistic effects of combining evidence levels and was succeeded by methods using simultaneous interrogation of subtype clustering from different data types, like iCluster [@shenIntegrativeClusteringMultiple2009], which jointly models cancer subtypes as latent variables from different data types, or TumorMap [@newtonTumorMapExploringMolecular2017], which uses similarity of molecular tumor profiles to embed samples into a standardized similarity space. A natural approach to encode sample similarity is graph-based: @wangSimilarityNetworkFusion2014 construct sample similarity networks for each data type individually and subsequently fuse those networks into a common similarity space, thereby performing joint vertical and horizontal data integration. In their setup, cancer subtypes emerge as connected components in the graph and edges between samples give information about from which data type evidence comes from. Interpretability is also a feature of Multi-Omics Factor Analysis (MOFA, @argelaguetMultiOmicsFactor2018), a versatile statistical framework that infers a low-dimensional representation and captures major sources of variation across data types. Latent factors underlying the representation can be linked to most relevant features and reveal shared variation between different omics layers. Recent technological advancement in the field of deep neuronal networks led to the development of methods for cancer subtype classification [@gaoDeepCCNovelDeep2019;@tabibuPanRenalCellCarcinoma2019], using molecular or histological features for classifier training. In contrast to other applications, classification by neuronal networks is a supervised task, meaning that the learned classifier can only be used to classify new samples, but does not detect novel subtypes once more data is available.

