### Skeletal muscle regeneration as a model for stem cell tumour? {#regeneration}

The ability of movement is an evolutionary advantage of all animals, and is powered by muscles. Vertebrate locomotion receives its power from striated, skeletal muscle, one of the three major muscle types in the body, that is composed from multiple bundled muscle fibres (fascicles). Each fibre is a multinucleated muscle cell formed by fusion of differentiated mononuclear muscle cells (myoblasts) and exhibits force and movement by coordinated activity of myosin II motor proteins within an actin filament scaffold. Skeletal muscle retains a remarkable ability to regenerate and adapt to changes in requirements, mediated by and dependent on muscle stem cells that reside in a *niche* between the muscle sarcolemma and the basal lamina of individual muscle fibres. Adult muscle stem cells are *bona fide* stem cells, being capable of both, self-renewal and myogenic differentiation, which ultimately leads to differentiated muscle cells [@almadaMolecularCircuitryStem2016; @guntherMyf5PositiveSatelliteCells2013].

Under homeostasis of uninjured muscle, muscle stem cells are characterised by expression of Paired box protein 7 (Pax7), a transcriptional regulator that actively maintains a state of restrained cell cycling called *quiescence*. Upon muscle trauma, otherwise quiescent muscle stem cells become activated through exposure to extrinsic, pro-myogenic stimuli and switch to a highly proliferative state. Activation and proliferation of muscle stem cells depends on expression of two transcriptional regulators, myogenic factor 5 (Myf5) and myogenic determintation protein (MyoD), and precedes commitment to differentiation [@braunTranscriptionalMechanismsRegulating2011]. Downregulation of Pax7 and expression of myogenin (MyoG) in a subset of activated muscle stem cells induces differentiation and ultimately leads cell-cycle exit and formation of myoblasts that fuse with other myoblasts or existing muscle fibres to repair the muscle [@braunTranscriptionalMechanismsRegulating2011]. Activated stem cells may also inhibit MyoD expression and re-instating quiescence, thereby replenishing the pool of muscle stem cells for future rounds of muscle repair.

Duchenne muscular dystrophy (DMD) is a genetic disorder with severe features of muscle weakness and decrease in the muscle mass (muscle wasting, atrophy). Dystrophin, the gene product causing DMD in affected individuals, plays a pivotal role in anchoring muscle fibres to the extracellular matrix, thereby allowing force to be transmitted to the skeletal parts of the muscle. Dystrophic fibres are prone to get damaged by mechanical stress and die after repeated muscle contraction. Such fibres are often replaced by fibrotic, adipose or connective tissue that is not able to transmit sufficient muscular force. Muscle degeneration elicits repair by expansion and differentiation of stem cells, but regenerated muscle fibres also lack a functional dystrophin such that chronic cycles of degeneration and regeneration are passed through. Until now, the role of muscle stem cells in DMD remains elusive, with only some evidence for a specialized role of dystrophin during stem cell division, but an important role of dystrophin for the pathological environment in disease progression.

A genetic and experimental model of DMD is the *mdx* mouse, whose muscles retain a lifelong capacity to regenerate fibres and exhibits loss of muscle fibres and extensive fibrosis [@boldrinSatelliteCellsDystrophic2015a]. Recently, it was shown that germline inactivation of the tumour suppressor p53 in chronically regenerating mdx mice develop rhabdomyosarcoma (RMS) [@camboniInductionRegenerativeMicroenvironment2012a; @chamberlainDystrophindeficientMdxMice2007], a rare and aggressive childhood cancer and the most common soft-tissue sarcoma in children and adolescents. Histologically, RMS resembles developing skeletal muscle and is marked by expression of actin and myosin as well as myogenic factors [@eldemellawyUpdateMolecularFindings2017]. RMS is subdivided into four subgroups, with alveolar RMS (ARMS) and embryonal RMS (ERMS) being two major subgroups accounting for nearly all childhood cases of RMS, while spindle cell RMS and pleomorphic RMS occurring mostly in adolescents. A broad molecular basis has been identified in RMS, with interference of myogenic differentiation and emergence of chromosomal aberrations being main drivers of cancer progression. For example, aberrant expression of Notch2, Yap1, members of the Wnt gene family and Tgf-1 signalling have been implicated in disruption of myogenic differentiation [@schaafFullTranscriptomeAnalysis2005; @judsonHippoPathwayMember2012; @chenGlycogenSynthaseKinase2014; @wangTGFv1SignalPathway2010]. On the other hand, expression of Egr1, Met and signalling by the Fgf family seem to maintain proliferation of RMS cells [@sarverMicroRNAMiR183Functions2010a; @taulliValidationMetTherapeutic2006; @wachtelFGFR4SignalingCouples2014]. Genomic amplifications and translocations, as well as loss of heterozygosity from specific whole chromosomes have been reported for ERMS and ARMS subtypes. Prominent examples include interference of Pax3 and Pax7 expression levels in ERMS, promoting migration and invasiveness [@chiappalupiDefectiveRAGEActivity2014; @bridgeGenomicGainsLosses2002], and Pax3-Foxo1 or Pax7-Foxo1 gene fusions in ARMS, leading to commitment of mesenchymal stem cells to the myogenic lineage by transactivation of MyoD or MyoG [@renMouseMesenchymalStem2008]. In addition to genetic mechanisms, epigenetic and small RNA-mediated mechanisms have also been described to deregulate myogenic differentiation and enable escape of RMS cells from suppressive mechanisms (see also chapters \@ref(mirna) and \@ref(epigenetic)).

RMS is marked by large heterogeneity that not only manifests in distinct subtypes, but also by different underlying genetic and epigenetic mechanisms. However, the cellular origin of RMS has remained elusive, despite large efforts to characterize the molecular basis of many RMS specimen in recent years. As introduced in chapter \@ref(csc), high tumour heterogeneity can emerge from a cellular origin with stem cell-like properties. Subsequently, the cellular origin of RMS could be discovered in the tissue-resident stem cells, e.g. muscle stem cells or mesenchymal stem cells [@hettmerMusclingUncoveringOrigins2010]. As such and for RMS subtypes showing features of myogenic differentiation, the *mdx* mouse model with its constant regeneration of skeletal muscle could be used as a model for stem cell-dependent tumorigenesis and serve the discovery of the cellular origin of RMS.
