### Genomic alterations transform cells into cancer cells {#smt}

While normal cells retain their ability to control the production and release of growth-promoting signals and thereby provide tissue architecture and homeostasis of cell number, cancer cells are characterised by chronic proliferation and constant re-entry into the growth-and-division cycle. The somatic mutation theory postulates that molecular events such as genomic mutations precede cell transformation (Fig. \@ref(fig:somatic-mutations)a), black lightning) and provide the cell with the ability to overcome cell control mechanisms. By such, transformed cancer cells are able to e.g. escape the control of growth suppressors, bypass mechanism of induced cell death, delay or avoid entry into cell senescence, induce angiogenesis and/or alter cell-to-cell contacts to activate invasion of surrounding tissue [@hanahanHallmarksCancerNext2011a]. At the core of this theory, mutations in so-called master genes, i.e. genes that have the potential to cause cancer (oncogenes) or genes that protect the cell from cancer progression (tumour suppressor genes), constitute the origin of cancer. 

The search for transformation-causing genome alterations accelerated through recent advances in high-throughput technologies which led to an impressive accumulation of data from large-scale genome sequencing projects like the [Cancer Genome Project](cancer.sanger.ac.uk) or [The Cancer Genome Atlas](cancergenome.nih.gov). Collectively, both projects list 77 million simple somatic mutations across cancer genomes from nearly 25,000 individuals in the International Cancer Genome Consortium [Data Portal Release 27](https://dcc.icgc.org/releases/release_27). However, the search did not reveal a single pattern of genetic alterations that is universal to most cancers. Instead, a tremendous genetic heterogeneity in underlying mechanisms of cancer formation emerged, despite very similar phenotypes.

The observed genetic heterogeneity among cancer and even within similar cancer types suggests that most individual tumours exhibit altered genome contexts (genes, regulatory elements and genomic topology), with different genomic mutations. The Genome Theory is an extension of the somatic mutation theory and seeks to explain cancer heterogeneity by additionally including cell population heterogeneity and the process of natural selection (@hengEvolutionaryMechanismCancer2010, fig. \@ref(fig:somatic-mutations)). Cancer formation is seen as an evolutionary process initiated through internal (e.g. somatic mutations) or external (e.g. environment, lifestlye, treatment) stress that results in genome context instability. Additional genetic or epigenetic mutations may occur in individual somatic cells with instable genomic contexts, increase the cell population heterogeneity and confer differences in fitness between somatic cells. Importantly, as genetic or epigenetic mutations are heritable and can be passed to a cells progeny, all requirements for natural selection are met and enables evolution of somatic cells within individual patients towards cancer.

```{r somatic-mutations, fig.scap = "Heterogeneity in the process of cancer formation.", fig.cap="Heterogeneity in the process of cancer formation. (a) Molecular events (straight arrows, exemplified for one cell) increase heterogeneity of the genomic context (colors) and confer differences in fitness between somatic cells. Oncogenic transformation (black lightning) enables positive natural selection and the evolution of cancer. (b) Cell population heterogeneity is additionally increased by influence of external factors onto genomic contexts.", fig.align="center", dpi=300, message=FALSE, warning=FALSE, error=FALSE}

fig_somatic_mutations <- multipanelfigure::multi_panel_figure(width = c(82, 64.5), height = 50, column_spacing = 0, unit = "mm", rows = 1, panel_label_type = "lower-alpha")
fig_somatic_mutations <- multipanelfigure::fill_panel(figure = fig_somatic_mutations, file.path("..", "figures", "natural_selection_cancer-01.png"), column = 1, row = 1, scaling = "fit")
fig_somatic_mutations <- multipanelfigure::fill_panel(figure = fig_somatic_mutations, file.path("..", "figures", "stratified_patients-01.png"), column = 2, row = 1, scaling = "fit")

fig_somatic_mutations
```

The occurence of genome-level alterations in an instable genome context is a stochastic process and therefore the probability of successful progression towards cancer is highest through alterations significantly impacting a cells phenotype. However, the stochastic nature complicates the prediction of which pathway will become dominant prior to tumour formation and renders the characterization of individual cancer pathways less meaningful. Ultimately, it impedes the establishment of a general model of cancer origin and obscures understanding of how cancer can be managed in classical clinical treatment.
