### The stem cell as a cancer cell of origin {#csc}

Similar to maintenance of tissue identity, the development of normal tissue requires complex crosstalk between cells, their local environment and the whole organ. Migration and porper localization of precursor cells is a prerequisite for formation of mature descendants that can carry out their tissue-specific function. The specific pattern of a cells tissue-forming division(s) has been termed its *lineage* [@chisholmCellLineage2001]. Dissection of such cell lineages revealed further a hierarchical organization and helped to identify interactions and molecular signalling pathways that are important in tissue development and diseases. However, unidirectional division alongside the cell lineage would quickly lead to exhaustion of a cells tissue-generative potential and calls for a mechanism like duplicating mitosis as proposed by the physiomitotic theory: **Stem cells** are multipotent unspecialized cells residing at the apex of a lineage, and are capable of both, the generation of progenitor cells with increasing lineage commitment and self-renewal, in order to regenerate and sustain the pool of stem cells. The inherent proliferative capacity and the ability to give rise to different, mature cell types renders stem cells particularly fascinating for the study of tissue development, regeneration and in the search for the cellular origin of cancer.

Cells with self-renewal capacity are of paramount importance for tumor growth, as they ensure long-term clonal growth. However, not all cancer cells possess self-renewal capacity and not all cancer cells of origin were bona-fide stem cells. So, how do cancer cells acquire their stemness, if not from normal tissue stem cells?

An important distinction has to be made between cancer cells of origin (*i.e.* the normal cell that acquires the first cancer-promoting mutation) and cancer stem cells, *i.e.* a cellular subset within a tumor that exclusively sustains malignant growth. Intertumoral heterogeneity, *i.e.* the variability among discrete tumor types arising from the same tissue, has put forward two hypothesis how cancer stem cells are formed: (A) All tumors originate from multipotent stem cells that accumuluate different genetic or epigenetic mutations through their extended longevity and therefore result in different tumor types or (B) different cells along the lineage hierarchy that still possess or can re-instigate proliferative capacity or prevent terminal differentiation (e.g. common or committed progenitor cells) constitute different cancer types upon oncogenic transformation [@perez-losadaStemcellHierarchySkin2003a, @visvaderCellsOriginCancer2011].

Both mechanisms inextricably link lineage descendance and differentiation state of precursor cells to cancer biology, such that activation of the same oncogenic pathway in tumors from different cell lineages or contexts may profoundly influence malignancy and tumor phenotype. Lineage dependency (add literature) therefore guides therapeutic approaches [@garrawayLineageDependencyLineagesurvival2006] ...

A straightforward approach to evaluate the oncogenic capacity of different lineage stem and precursor cell populations relies on reproducible separation of functionally defined subpopulations using e.g. cell sorting techniques. Relevant oncogenic lesions are introduced *ex vivo*, together with a flourescent reporter, into each precursor cell population and genetically altered cells are transplanted orthotopically into immunocompromised mice. Emergence of pre-neoplastic or neoplastic tissue from transduced subpopulations serves as readout for evaluation of oncogenic potential for each subpopulation. Complimentary, and with sufficient knowledge about cell-specific promoters, *in vivo* conditional targeting of cell populations is also conceivable. This approach makes use of genetic mouse models to conditionally activate either an oncogene or inactivate a tumor supressor gene, e.g. by Cre-mediated deletion, in different lineage subpopulations. Depending on the activated cell-specific promoter, different cancer subtypes might arise and reveal the cellular origin of the specifc cancer subtype from within the cell lineage [@Hayashi;@visvaderCellsOriginCancer2011]. However, for many tissues and organs, established lineages and knowledge of cell specific promoters are missing, and therefore hamper the approach described above.
